# Linear Algebra

In [1]:
import numpy as np

In [3]:
matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [4]:
matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [6]:
matrix.I # inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [7]:
matrix * matrix.I

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.55111512e-17,  1.00000000e+00, -2.22044605e-16],
        [ 5.55111512e-17, -1.11022302e-16,  1.00000000e+00]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## make array immutable

In [10]:
array = np.arange(10)
array.flags.writeable = False
array[5] = 1234

ValueError: assignment destination is read-only

In [11]:
rhs = np.matrix([[11],[22],[33]])

In [12]:
matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

In [14]:
solution = matrix.I * rhs
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [16]:
matrix * solution - rhs

matrix([[ 1.77635684e-15],
        [-3.55271368e-15],
        [ 0.00000000e+00]])

In [17]:
# more efficient for large matrices
from numpy.linalg import solve
solve(matrix, rhs)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [18]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))