In [1]:
import numpy as np
print (np.__version__)

1.14.0


# Creating numpy array from list

In [3]:
my_list = [7, 0, 4, 2, 1]
my_array_from_list = np.array(my_list)
my_array_from_list

array([7, 0, 4, 2, 1])

In [4]:
my_array_from_list.dtype

dtype('int64')

In [5]:
my_list = [-7, 0, 4.0, 2, 1j]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-7.+0.j,  0.+0.j,  4.+0.j,  2.+0.j,  0.+1.j])

In [6]:
my_array_from_list.dtype

dtype('complex128')

#### Scalar multiplication

In [8]:
my_array_from_list * 10 # each element will be multiplied by 10

array([-70. +0.j,   0. +0.j,  40. +0.j,  20. +0.j,   0.+10.j])

#### Same goes with other operations too

In [12]:
my_array_from_list = np.array([10, 15, 21, 32, 8])
print(my_array_from_list, '+ 10 ::',my_array_from_list + 10)
print(my_array_from_list, '- 10 ::',my_array_from_list - 10)
print(my_array_from_list, '/ 10 ::',my_array_from_list / 10)
print(my_array_from_list, '// 10 ::',my_array_from_list // 10)
print(my_array_from_list, '% 10 ::',my_array_from_list % 10)

[10 15 21 32  8] + 10 :: [20 25 31 42 18]
[10 15 21 32  8] - 10 :: [ 0  5 11 22 -2]
[10 15 21 32  8] / 10 :: [1.  1.5 2.1 3.2 0.8]
[10 15 21 32  8] // 10 :: [1 1 2 3 0]
[10 15 21 32  8] % 10 :: [0 5 1 2 8]


# NumPy array creation using NumPy's methods

In [13]:
np.arange(0, 12, 3) # arange works similar to range 

array([0, 3, 6, 9])

In [14]:
np.arange(0, 12, 3).size

4

In [17]:
np.linspace(1, 10, num=6, endpoint=False, retstep=True) 
# num ==> total number of elements in sample
# endpoint = True ==> include stop else not
# retstep = True ==> return (`samples`, `step`) ==> step is spacing between samples.

(array([1. , 2.5, 4. , 5.5, 7. , 8.5]), 1.5)

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((4, 3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
my_array = np.ones((4, 3),dtype='int')
my_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
print(my_array.shape)
print(my_array.size)

(4, 3)
12


# Slicing

In [29]:
my_array = np.arange(0, 12)
print(my_array)
print(my_array[0])
print(my_array[2:5])
print(my_array[5:2:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
[2 3 4]
[5 4 3]


In [31]:
my_array= np.arange(24)
my_array.shape = (6,4)
my_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
print(my_array[2,1]) # row index, column index
print(my_array[2:5,1])
print(my_array[3:6,1:3])
print(my_array[:,2])
print(my_array[:,0:3])

9
[ 9 13 17]
[[13 14]
 [17 18]
 [21 22]]
[ 2  6 10 14 18 22]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]


In [42]:
my_array = np.arange(32)
my_array.shape = (2, 4, 4)
my_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [52]:
print(my_array[1]) # matrix , row , column 
print()
print(my_array[:,1])
print()
print(my_array[:,:,1])
print()
print(my_array[:,0,1])
print()
print(my_array[0,:,1])
print()
print(my_array[0,2,3])

[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]]

[[ 1  5  9 13]
 [17 21 25 29]]

[ 1 17]

[ 1  5  9 13]

11


## Boolean Mask Arrays

In [56]:
my_array = np.arange(0, 12)
print(my_array)
my_index = [False,True,False,True,False,True,False,True,False,True,False,True]
print(my_array[my_index])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  3  5  7  9 11]


[False, True, False, True, False, True, False, True, False, True, False, True]

In [57]:
print(my_array[my_array%3 == 0])

[0 3 6 9]


In [62]:
print(np.logical_and(my_array%3==0, my_array%2==0))
print(my_array[np.logical_and(my_array%3==0, my_array%2==0)])

[ True False False False False False  True False False False False False]
[0 6]
