In [1]:
import numpy as np
print (np.__version__)

1.14.0


# Creating numpy array from list

In [3]:
my_list = [7, 0, 4, 2, 1]
my_array_from_list = np.array(my_list)
my_array_from_list

array([7, 0, 4, 2, 1])

In [4]:
my_array_from_list.dtype

dtype('int64')

In [5]:
my_list = [-7, 0, 4.0, 2, 1j]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-7.+0.j,  0.+0.j,  4.+0.j,  2.+0.j,  0.+1.j])

In [6]:
my_array_from_list.dtype

dtype('complex128')

## Scalar multiplication

In [7]:
my_array_from_list * 10

array([-70. +0.j,   0. +0.j,  40. +0.j,  20. +0.j,   0.+10.j])