In [2]:
import numpy as np

### Array multiplication

In [4]:
my_array = np.arange(7) 
print(my_array)
print(my_array * my_array) # if multiply 1d array, element wise multiplication happens

[0 1 2 3 4 5 6]
[ 0  1  4  9 16 25 36]


In [29]:
my_array = np.arange(24)
my_array.shape = (2,4,3)

In [10]:
print('my_array  ::\n ', my_array)
print('\n\n5 * my_array - 4  ::\n ', 5 * my_array - 4)
print('\n\nmy_array.reshape(3,2,4)  ::\n ', my_array.reshape(3,2,4))
print('\n\nmy_array.reshape(2,12)  ::\n ', my_array.reshape(2,12))

my_array  ::
  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


5 * my_array - 4  ::
  [[[ -4   1   6]
  [ 11  16  21]
  [ 26  31  36]
  [ 41  46  51]]

 [[ 56  61  66]
  [ 71  76  81]
  [ 86  91  96]
  [101 106 111]]]


my_array.reshape(3,2,4)  ::
  [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


my_array.reshape(2,12)  ::
  [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [15]:
my_array1 = my_array.reshape(2,12)
my_array2 = my_array.reshape(12,2)
print(my_array1)
print(my_array2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [18]:
print(my_array1 * my_array1) # element wise element multiplication
my_array1 * my_array2 # it won't work as matrix multiplication

[[  0   1   4   9  16  25  36  49  64  81 100 121]
 [144 169 196 225 256 289 324 361 400 441 484 529]]


ValueError: operands could not be broadcast together with shapes (2,12) (12,2) 

In [14]:
np.dot(my_array1, my_array2) # for matrix multiplication

array([[1012, 1078],
       [2596, 2806]])

## array aggregation

In [32]:
print(my_array)
my_array.shape

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


(2, 4, 3)

In [22]:
my_array.sum() # sum of all elements

276

In [23]:
my_array.sum(axis=0) # sum matrix wise

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [27]:
my_array.sum(axis=1) # sum column wise

array([[18, 22, 26],
       [66, 70, 74]])

In [26]:
my_array.sum(axis=2) # sum row wise # each element of return array is sum of each row 

array([[ 3, 12, 21, 30],
       [39, 48, 57, 66]])

In [30]:
my_array1 = np.arange(12).reshape(4,3)

In [37]:
print(my_array1 * my_array )# multiply 2d array and 3d array

[[[  0   1   4]
  [  9  16  25]
  [ 36  49  64]
  [ 81 100 121]]

 [[  0  13  28]
  [ 45  64  85]
  [108 133 160]
  [189 220 253]]]


## Structured Arrays

In [38]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [39]:
people_array = np.zeros((4,), dtype=person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [40]:
people_array[3] = ('Delta', 73, 205, 34)
people_array[0] = ('Alpha', 65, 112, 23)
people_array

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [50]:
people_array[2] = ('very long string with long height and weight and age', 73000, 205, 34.5)

In [53]:
people_array # name will be first 6 character and age will be converted to int

array([(b'Alpha', 6.5e+01, 112., 23), (b'', 0.0e+00,   0.,  0),
       (b'very l', 7.3e+04, 205., 34), (b'Delta', 7.3e+01, 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

### can create 3D array also

In [57]:
people_3D_array = np.ones((4,3,2), dtype=person_data_def)
people_3D_array

array([[[(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)]],

       [[(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)]],

       [[(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)]],

       [[(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)],
        [(b'1', 1., 1., 1), (b'1', 1., 1., 1)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [58]:
people_3D_array['height']

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [61]:
people_3D_array[['height', 'weight']]

array([[[(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)]],

       [[(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)]],

       [[(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)]],

       [[(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)],
        [(1., 1.), (1., 1.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

In [62]:
person_2D_array = np.rec.array([('Delta', 73, 205, 34),('Alpha', 65, 112, 23)],dtype=person_data_def)
person_2D_array

rec.array([(b'Delta', 73., 205., 34), (b'Alpha', 65., 112., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [63]:
person_2D_array[0].age

34

In [64]:
person_2D_array.age

array([34, 23])