# Adding and Removing Elements 

In [ ]:
import numpy as np

In [5]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
b=np.append(a, [5,6,7,8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [9]:
b.reshape(2,2,7)

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23,  5,  6,  7,  8]]])

In [11]:
c = np.array(np.arange(24)).reshape(2,3,4) * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [12]:
np.append(a,c, axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [13]:
np.append(a,c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [14]:
np.append(a,c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [15]:
np.hstack((a,c))

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [16]:
np.insert (c, 1, 444, axis=0)

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [17]:
np.insert(c, 1, 444, axis=1)

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [18]:
np.insert (c, 1, 444, axis=2)

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [19]:
np.delete(c, 1, axis=0)

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]]])

In [20]:
np.delete(c, 1, axis=1)

array([[[  3,  13,  23,  33],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [203, 213, 223, 233]]])

In [21]:
np.delete(c, 1, axis=2)

array([[[  3,  23,  33],
        [ 43,  63,  73],
        [ 83, 103, 113]],

       [[123, 143, 153],
        [163, 183, 193],
        [203, 223, 233]]])

# Joining and Splitting

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [23]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
c = np.array([[5, 6], [7, 8]])
np.concatenate((a, c), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
arrays

array([[[ 0.69494989, -0.59771824,  0.06771796, -0.25852865],
        [-0.78257949,  0.50005232, -0.69758749, -0.08658936],
        [ 0.70495812, -0.35259042, -0.16139727, -0.27223062]],

       [[-0.89797653, -0.11976978,  0.85060641, -0.59959174],
        [-0.05541204, -1.38693108,  0.18541737,  0.11012022],
        [-0.06554153,  0.18170891,  0.08745472, -0.30709763]],

       [[-1.12934978, -0.02554091, -0.18802246, -0.62369563],
        [-0.48788512,  0.26446505, -0.23418642, -0.60727254],
        [ 0.08365216,  0.13464875,  0.70544288, -0.68431148]],

       [[-1.56936477,  0.58274704,  0.17536639, -1.45633994],
        [ 1.28558231,  0.98144966,  1.37838852,  0.14602435],
        [-0.41911462,  0.40113936, -0.15373199,  0.61460473]],

       [[-0.77856559,  0.11601228,  3.03866267, -0.619738  ],
        [ 0.80817921,  0.05196294, -1.00682792,  1.57979812],
        [-0.60823132,  0.4330149 ,  0.67511446,  0.06516716]]])

In [28]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [29]:
stack0

array([[[ 0.69494989, -0.59771824,  0.06771796, -0.25852865],
        [-0.78257949,  0.50005232, -0.69758749, -0.08658936],
        [ 0.70495812, -0.35259042, -0.16139727, -0.27223062]],

       [[-0.89797653, -0.11976978,  0.85060641, -0.59959174],
        [-0.05541204, -1.38693108,  0.18541737,  0.11012022],
        [-0.06554153,  0.18170891,  0.08745472, -0.30709763]],

       [[-1.12934978, -0.02554091, -0.18802246, -0.62369563],
        [-0.48788512,  0.26446505, -0.23418642, -0.60727254],
        [ 0.08365216,  0.13464875,  0.70544288, -0.68431148]],

       [[-1.56936477,  0.58274704,  0.17536639, -1.45633994],
        [ 1.28558231,  0.98144966,  1.37838852,  0.14602435],
        [-0.41911462,  0.40113936, -0.15373199,  0.61460473]],

       [[-0.77856559,  0.11601228,  3.03866267, -0.619738  ],
        [ 0.80817921,  0.05196294, -1.00682792,  1.57979812],
        [-0.60823132,  0.4330149 ,  0.67511446,  0.06516716]]])

In [30]:
stack1

array([[[ 0.69494989, -0.59771824,  0.06771796, -0.25852865],
        [-0.89797653, -0.11976978,  0.85060641, -0.59959174],
        [-1.12934978, -0.02554091, -0.18802246, -0.62369563],
        [-1.56936477,  0.58274704,  0.17536639, -1.45633994],
        [-0.77856559,  0.11601228,  3.03866267, -0.619738  ]],

       [[-0.78257949,  0.50005232, -0.69758749, -0.08658936],
        [-0.05541204, -1.38693108,  0.18541737,  0.11012022],
        [-0.48788512,  0.26446505, -0.23418642, -0.60727254],
        [ 1.28558231,  0.98144966,  1.37838852,  0.14602435],
        [ 0.80817921,  0.05196294, -1.00682792,  1.57979812]],

       [[ 0.70495812, -0.35259042, -0.16139727, -0.27223062],
        [-0.06554153,  0.18170891,  0.08745472, -0.30709763],
        [ 0.08365216,  0.13464875,  0.70544288, -0.68431148],
        [-0.41911462,  0.40113936, -0.15373199,  0.61460473],
        [-0.60823132,  0.4330149 ,  0.67511446,  0.06516716]]])

In [32]:
stack2

array([[[ 0.69494989, -0.89797653, -1.12934978, -1.56936477,
         -0.77856559],
        [-0.59771824, -0.11976978, -0.02554091,  0.58274704,
          0.11601228],
        [ 0.06771796,  0.85060641, -0.18802246,  0.17536639,
          3.03866267],
        [-0.25852865, -0.59959174, -0.62369563, -1.45633994,
         -0.619738  ]],

       [[-0.78257949, -0.05541204, -0.48788512,  1.28558231,
          0.80817921],
        [ 0.50005232, -1.38693108,  0.26446505,  0.98144966,
          0.05196294],
        [-0.69758749,  0.18541737, -0.23418642,  1.37838852,
         -1.00682792],
        [-0.08658936,  0.11012022, -0.60727254,  0.14602435,
          1.57979812]],

       [[ 0.70495812, -0.06554153,  0.08365216, -0.41911462,
         -0.60823132],
        [-0.35259042,  0.18170891,  0.13464875,  0.40113936,
          0.4330149 ],
        [-0.16139727,  0.08745472,  0.70544288, -0.15373199,
          0.67511446],
        [-0.27223062, -0.30709763, -0.68431148,  0.61460473,
          0

### split

In [36]:
temp = np.arange(6)
np.split(temp,1)

[array([0, 1, 2, 3, 4, 5])]

In [39]:
np.split(temp,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [40]:
stack0.shape

(5, 3, 4)

In [41]:
np.split(stack0, 5, axis=0)

[array([[[ 0.69494989, -0.59771824,  0.06771796, -0.25852865],
         [-0.78257949,  0.50005232, -0.69758749, -0.08658936],
         [ 0.70495812, -0.35259042, -0.16139727, -0.27223062]]]),
 array([[[-0.89797653, -0.11976978,  0.85060641, -0.59959174],
         [-0.05541204, -1.38693108,  0.18541737,  0.11012022],
         [-0.06554153,  0.18170891,  0.08745472, -0.30709763]]]),
 array([[[-1.12934978, -0.02554091, -0.18802246, -0.62369563],
         [-0.48788512,  0.26446505, -0.23418642, -0.60727254],
         [ 0.08365216,  0.13464875,  0.70544288, -0.68431148]]]),
 array([[[-1.56936477,  0.58274704,  0.17536639, -1.45633994],
         [ 1.28558231,  0.98144966,  1.37838852,  0.14602435],
         [-0.41911462,  0.40113936, -0.15373199,  0.61460473]]]),
 array([[[-0.77856559,  0.11601228,  3.03866267, -0.619738  ],
         [ 0.80817921,  0.05196294, -1.00682792,  1.57979812],
         [-0.60823132,  0.4330149 ,  0.67511446,  0.06516716]]])]

In [43]:
len(np.split(stack0, 5, axis=0))

5

In [44]:
np.split(stack0, 3, axis=1)

[array([[[ 0.69494989, -0.59771824,  0.06771796, -0.25852865]],
 
        [[-0.89797653, -0.11976978,  0.85060641, -0.59959174]],
 
        [[-1.12934978, -0.02554091, -0.18802246, -0.62369563]],
 
        [[-1.56936477,  0.58274704,  0.17536639, -1.45633994]],
 
        [[-0.77856559,  0.11601228,  3.03866267, -0.619738  ]]]),
 array([[[-0.78257949,  0.50005232, -0.69758749, -0.08658936]],
 
        [[-0.05541204, -1.38693108,  0.18541737,  0.11012022]],
 
        [[-0.48788512,  0.26446505, -0.23418642, -0.60727254]],
 
        [[ 1.28558231,  0.98144966,  1.37838852,  0.14602435]],
 
        [[ 0.80817921,  0.05196294, -1.00682792,  1.57979812]]]),
 array([[[ 0.70495812, -0.35259042, -0.16139727, -0.27223062]],
 
        [[-0.06554153,  0.18170891,  0.08745472, -0.30709763]],
 
        [[ 0.08365216,  0.13464875,  0.70544288, -0.68431148]],
 
        [[-0.41911462,  0.40113936, -0.15373199,  0.61460473]],
 
        [[-0.60823132,  0.4330149 ,  0.67511446,  0.06516716]]])]

In [47]:
import pprint
pprint.pprint(np.split(stack0, 4, axis=2))

[array([[[ 0.69494989],
        [-0.78257949],
        [ 0.70495812]],

       [[-0.89797653],
        [-0.05541204],
        [-0.06554153]],

       [[-1.12934978],
        [-0.48788512],
        [ 0.08365216]],

       [[-1.56936477],
        [ 1.28558231],
        [-0.41911462]],

       [[-0.77856559],
        [ 0.80817921],
        [-0.60823132]]]),
 array([[[-0.59771824],
        [ 0.50005232],
        [-0.35259042]],

       [[-0.11976978],
        [-1.38693108],
        [ 0.18170891]],

       [[-0.02554091],
        [ 0.26446505],
        [ 0.13464875]],

       [[ 0.58274704],
        [ 0.98144966],
        [ 0.40113936]],

       [[ 0.11601228],
        [ 0.05196294],
        [ 0.4330149 ]]]),
 array([[[ 0.06771796],
        [-0.69758749],
        [-0.16139727]],

       [[ 0.85060641],
        [ 0.18541737],
        [ 0.08745472]],

       [[-0.18802246],
        [-0.23418642],
        [ 0.70544288]],

       [[ 0.17536639],
        [ 1.37838852],
        [-0.15373199]],

 

# Rearranging Array Elements

In [49]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
np.fliplr(a)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [52]:
np.flipud(a)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [53]:
np.roll(a, 5)

array([[[19, 20, 21, 22],
        [23,  0,  1,  2],
        [ 3,  4,  5,  6]],

       [[ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [55]:
np.roll(a, -5)

array([[[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23,  0],
        [ 1,  2,  3,  4]]])

In [56]:
np.rot90(a)

array([[[ 8,  9, 10, 11],
        [20, 21, 22, 23]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 0,  1,  2,  3],
        [12, 13, 14, 15]]])

In [57]:
np.rot90(a, k=-1)

array([[[12, 13, 14, 15],
        [ 0,  1,  2,  3]],

       [[16, 17, 18, 19],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [ 8,  9, 10, 11]]])